### ISSUE TITLE
How to run hybrid training of your codes?

### ISSUE THREAD

**Issue by Chan-1996** [ZO-Bench/ZO-LLM#3]
Hi,
     I cannot find any codes about hybrid training with ZO and FO, have you included this part in trainer.py?

**Comment by NormalUhr** [comment]
Hi, thanks for your interests in our work. The codes related to the Sec. 5 of our paper were originally written in quite a ad-hoc manner, so we did not release them with the code main branch. We are still refactoring and cleaning that part and will release them as soon as we finish them. Thank you!

**Comment by Chan-1996** [comment]
I see, thank you for your response！

**Comment by SunMinqiu** [comment]
Hi, I noticed that this issue was closed a while ago, but I'm still very interested in the hybrid training code (ZO + FO). Has there been any update on releasing this part of the code? I would really appreciate it if you could share it, as I'm currently conducting research in this area and the hybrid training implementation would be very helpful for my work. Thank you!
